// panel/themes.js — Theme palettes
window.XRAY_Themes = {
  'catppuccin-mocha': {
    name: 'Catppuccin Mocha',
    dot: '#cba6f7',
    vars: {
      '--xr-bg':      '#1e1e2e',
      '--xr-bg2':     '#181825',
      '--xr-bg3':     '#313244',
      '--xr-surface': '#45475a',
      '--xr-overlay': '#6c7086',
      '--xr-text':    '#cdd6f4',
      '--xr-subtext': '#a6adc8',
      '--xr-accent':  '#cba6f7',
      '--xr-blue':    '#89b4fa',
      '--xr-green':   '#a6e3a1',
      '--xr-red':     '#f38ba8',
      '--xr-yellow':  '#f9e2af',
      '--xr-orange':  '#fab387',
      '--xr-teal':    '#94e2d5',
      '--xr-pink':    '#f5c2e7',
      '--xr-border':  '#45475a',
    }
  },
  'catppuccin-latte': {
    name: 'Catppuccin Latte',
    dot: '#8839ef',
    vars: {
      '--xr-bg':      '#eff1f5',
      '--xr-bg2':     '#e6e9ef',
      '--xr-bg3':     '#dce0e8',
      '--xr-surface': '#ccd0da',
      '--xr-overlay': '#9ca0b0',
      '--xr-text':    '#4c4f69',
      '--xr-subtext': '#6c6f85',
      '--xr-accent':  '#8839ef',
      '--xr-blue':    '#1e66f5',
      '--xr-green':   '#40a02b',
      '--xr-red':     '#d20f39',
      '--xr-yellow':  '#df8e1d',
      '--xr-orange':  '#fe640b',
      '--xr-teal':    '#179299',
      '--xr-pink':    '#ea76cb',
      '--xr-border':  '#bcc0cc',
    }
  },
  'dracula': {
    name: 'Dracula',
    dot: '#bd93f9',
    vars: {
      '--xr-bg':      '#282a36',
      '--xr-bg2':     '#21222c',
      '--xr-bg3':     '#44475a',
      '--xr-surface': '#44475a',
      '--xr-overlay': '#6272a4',
      '--xr-text':    '#f8f8f2',
      '--xr-subtext': '#6272a4',
      '--xr-accent':  '#bd93f9',
      '--xr-blue':    '#6272a4',
      '--xr-green':   '#50fa7b',
      '--xr-red':     '#ff5555',
      '--xr-yellow':  '#f1fa8c',
      '--xr-orange':  '#ffb86c',
      '--xr-teal':    '#8be9fd',
      '--xr-pink':    '#ff79c6',
      '--xr-border':  '#44475a',
    }
  },
  'nord': {
    name: 'Nord',
    dot: '#88c0d0',
    vars: {
      '--xr-bg':      '#2e3440',
      '--xr-bg2':     '#242933',
      '--xr-bg3':     '#3b4252',
      '--xr-surface': '#434c5e',
      '--xr-overlay': '#4c566a',
      '--xr-text':    '#eceff4',
      '--xr-subtext': '#d8dee9',
      '--xr-accent':  '#88c0d0',
      '--xr-blue':    '#81a1c1',
      '--xr-green':   '#a3be8c',
      '--xr-red':     '#bf616a',
      '--xr-yellow':  '#ebcb8b',
      '--xr-orange':  '#d08770',
      '--xr-teal':    '#8fbcbb',
      '--xr-pink':    '#b48ead',
      '--xr-border':  '#4c566a',
    }
  }
};
