// panel/themes.js — Theme palettes (shadcn/Linear-inspired)
window.XRAY_Themes = {
  'zinc': {
    name: 'Zinc Dark',
    dot: '#a1a1aa',
    vars: {
      '--xr-bg':       '#09090b',
      '--xr-bg2':      '#18181b',
      '--xr-bg3':      '#27272a',
      '--xr-surface':  '#3f3f46',
      '--xr-overlay':  '#52525b',
      '--xr-text':     '#fafafa',
      '--xr-subtext':  '#a1a1aa',
      '--xr-muted':    '#71717a',
      '--xr-accent':   '#e4e4e7',
      '--xr-blue':     '#60a5fa',
      '--xr-green':    '#4ade80',
      '--xr-red':      '#f87171',
      '--xr-yellow':   '#fbbf24',
      '--xr-orange':   '#fb923c',
      '--xr-purple':   '#c084fc',
      '--xr-border':   '#27272a',
      '--xr-ring':     '#52525b',
      '--xr-radius':   '6px',
    }
  },
  'mocha': {
    name: 'Catppuccin Mocha',
    dot: '#cba6f7',
    vars: {
      '--xr-bg':       '#11111b',
      '--xr-bg2':      '#1e1e2e',
      '--xr-bg3':      '#313244',
      '--xr-surface':  '#45475a',
      '--xr-overlay':  '#585b70',
      '--xr-text':     '#cdd6f4',
      '--xr-subtext':  '#bac2de',
      '--xr-muted':    '#6c7086',
      '--xr-accent':   '#cba6f7',
      '--xr-blue':     '#89b4fa',
      '--xr-green':    '#a6e3a1',
      '--xr-red':      '#f38ba8',
      '--xr-yellow':   '#f9e2af',
      '--xr-orange':   '#fab387',
      '--xr-purple':   '#cba6f7',
      '--xr-border':   '#313244',
      '--xr-ring':     '#45475a',
      '--xr-radius':   '6px',
    }
  },
  'dracula': {
    name: 'Dracula',
    dot: '#bd93f9',
    vars: {
      '--xr-bg':       '#191a21',
      '--xr-bg2':      '#282a36',
      '--xr-bg3':      '#3d3f4f',
      '--xr-surface':  '#44475a',
      '--xr-overlay':  '#565970',
      '--xr-text':     '#f8f8f2',
      '--xr-subtext':  '#c8ccd8',
      '--xr-muted':    '#6272a4',
      '--xr-accent':   '#bd93f9',
      '--xr-blue':     '#8be9fd',
      '--xr-green':    '#50fa7b',
      '--xr-red':      '#ff5555',
      '--xr-yellow':   '#f1fa8c',
      '--xr-orange':   '#ffb86c',
      '--xr-purple':   '#bd93f9',
      '--xr-border':   '#44475a',
      '--xr-ring':     '#6272a4',
      '--xr-radius':   '6px',
    }
  },
  'nord': {
    name: 'Nord',
    dot: '#88c0d0',
    vars: {
      '--xr-bg':       '#191c24',
      '--xr-bg2':      '#242933',
      '--xr-bg3':      '#2e3440',
      '--xr-surface':  '#3b4252',
      '--xr-overlay':  '#434c5e',
      '--xr-text':     '#eceff4',
      '--xr-subtext':  '#d8dee9',
      '--xr-muted':    '#4c566a',
      '--xr-accent':   '#88c0d0',
      '--xr-blue':     '#81a1c1',
      '--xr-green':    '#a3be8c',
      '--xr-red':      '#bf616a',
      '--xr-yellow':   '#ebcb8b',
      '--xr-orange':   '#d08770',
      '--xr-purple':   '#b48ead',
      '--xr-border':   '#3b4252',
      '--xr-ring':     '#4c566a',
      '--xr-radius':   '6px',
    }
  }
};
